version: '3'
services:
  # Application Dockerfile-db is in the main folder
  app:
    build:
      context: .
      dockerfile: Dockerfile

  # db is in the db folder
  db:
    build:
      context: db
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always

