@startuml

actor "HR Advisor" as HR
actor "Department Manager" as Manager

rectangle Database

rectangle "HR System" {
    usecase UC1 as "Produce a report on the salaries of the employees"
    usecase UC2 as "Produce a report on the salaries of the employees in a department"
    usecase UC3 as "Produce a report on the salaries of the employees in HR department"
    usecase UC4 as "Get salaries by role"
    usecase UC5 as "Add employees' details"
    usecase UC6 as "View Employees' details"
    usecase UC7 as "Update Employees' details"
    usecase UC8 as "Delete Employees' details"


usecase UCa as " Print salaries report of employees"
usecase UCb as " Print salaries report of employees in a department"
usecase UCc as " Print salaries report of employees in HR"
usecase UCd as " Print Salaries"
usecase UCe as "Add employees' details"
usecase UCf as "View employees' details"
usecase UCg as "Update employees' details"
usecase UCh as "Delete employees' details"


    HR - UC1
    HR - UC2
    Manager - UC3
    HR - UC4
    HR - UC5
    HR - UC6
    HR - UC7
    HR - UC8


    UC1 ..> UCa : include
    UC2 ..> UCb : include
    UC3 ..> UCc : include
    UC4 ..> UCd : include
    UC5 ..> UCe : include
    UC6 ..> UCf : include
    UC7 ..> UCg : include
    UC8 ..> UCh : include


    UC1 -Database
    UC2 -Database
    UC3 -Database
    UC4 -Database
    UC5 -Database
    UC6 -Database
    UC7 -Database
    UC8 -Database


}

@enduml